id = "my-extension"
name = "My extension"
version = "0.0.1"
schema_version = 1
authors = ["Your Name <you@example.com>"]
description = "My cool extension"
repository = "https://github.com/your-name/my-klyx-extension"
# The size of requested memory for WebAssembly Environment (in MB)
requested_memory_size = 1
